x-base_service: &base_service
    networks:
      - sd_network
    ports:
      - "37861:7860"
    volumes:
      - &v1 /cargo/docker-storage/sd/data:/data
      - &v2 ./output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]

name: webui-docker

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - *v1

  auto: &automatic
    <<: *base_service
    profiles: ["auto"]
    build: ./services/AUTOMATIC1111
    image: sd-auto:78
    environment:
      - CLI_ARGS=--allow-code --xformers --enable-insecure-extension-access --api --gradio-img2img-tool color-sketch

  auto-full: &automatic
    <<: *base_service
    profiles: ["auto-full"]
    build: ./services/AUTOMATIC1111
    image: sd-auto:58
    environment:
      - CLI_ARGS=--allow-code --xformers --enable-insecure-extension-access --api --gradio-img2img-tool color-sketch --precision full --no-half

  auto-cpu:
    <<: *automatic
    profiles: ["auto-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--no-half --precision full --allow-code --enable-insecure-extension-access --api --gradio-img2img-tool color-sketch

  comfy: &comfy
    <<: *base_service
    profiles: ["comfy"]
    build: ./services/comfy/
    image: sd-comfy:7
    environment:
      - CLI_ARGS=


  comfy-cpu:
    <<: *comfy
    profiles: ["comfy-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--cpu


networks:
  sd_network:
    driver: bridge
